make venv

diff --git a/make_env b/make_env
--- a/make_env
+++ b/make_env
@@ -1,5 +1,18 @@
 # !/usr/bin/env bash
 # -*-: coding: utf-8 -*-
 
-virtualenv py2 -p python2.7
-virtualenv py3 -p python3
+ENV_DIR="py3"
+if [[ -d "$ENV_DIR" ]];
+then
+    echo "Deleting Exist ENV_DIR: $ENV_DIR"
+    rm -rf $ENV_DIR
+    echo "✅Completed!"
+fi
+echo "Creating New Python 3(>= 3.4) Environment"
+python3 -m venv $ENV_DIR
+if [[ $? -eq 0 ]];
+then
+    echo "✅Completed!"
+else
+    echo "✅Failed!"
+fi
